### ISSUE TITLE
Update usage

### ISSUE THREAD

**Issue by La-Pierre** [ANSSI-FR/SecAESSTM32#1]
Hi,
The documentation seems to not be up to date as the example of the AES execution given in the README (bellow) for the aes "easy use" primitive is still taking the length as a parameter.
```
UINT Mode;
STRUCT_AES aes_struct;
UCHAR key[16] = {0x2b,0x7e, 0x15, 0x16 ,0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c};		
UCHAR in[16] = {0x32,0x43, 0xf6, 0xa8, 0x88, 0x5a, 0x30 , 0x8d, 0x31, 0x31, 0x98, 0xa2, 0xe0, 0x37, 0x07, 0x34};
Mode = MODE_KEYINIT|MODE_AESINIT_ENC|MODE_ENC;
ret = aes(Mode, &aes_struct, key, 16, in, 16, out, 16);
```
The incode documentation as well mentions `key_size`, `input_size` and `output_size` (in `aes.c`) even if the aes type is 128 bit and the text length is set to 128 bit.

Thank you for your work !

**Comment by prouff** [comment]
Corrected. Thank you!
